### PR TITLE
Fix episode counter not being incremented in dqn and a2c agents

### PR DESCRIPTION
**Pull request by cesar0094**
The outer while loop in the agent's train method was checking that the
current episode is not greater than the requested number of episodes but
the episode counter was not being incremented. This caused an infinite
loop if you did not specify number of steps.

### CODE REVIEW

**Comment by giranntu** [comment]
I have run the sample and training worked without the infinite loop, does this necessary in what cases?

**Comment by cesar0094** [comment]
> I have run the sample and training worked without the infinite loop, does this necessary in what cases?

That's correct, it does not happen in all cases. When you provide `n_steps`, the training stops correctly but if you don't, then `stop_training` will never be `True` and `episode` remains `0`.

**Comment by spacewalkingninja** [comment]
> > I have run the sample and training worked without the infinite loop, does this necessary in what cases?
> 
> That's correct, it does not happen in all cases. When you provide `n_steps`, the training stops correctly but if you don't, then `stop_training` will never be `True` and `episode` remains `0`.

wanna make documentation for this?

**Comment by cesar0094** [comment]
Rebased on master.

**Comment by cesar0094** [comment]
> wanna make documentation for this?

Sure, I can add a docstring or where did you have in mind?

**Pull request merged**
