### PR TITLE
[WIP] Adding Extra Tests

### PR DESCRIPTION
**Pull request by funlyonions**
Hey, 

Derplypurple here. I'm merging the tests I started so far. It's seriously not much. I should be able to cram some to completion by the end of tonight. Let's find out.

### CODE REVIEW

**Comment by funlyonions** [comment]
There are some tests I'd like you to review. I know I have some problems with the indicators, though I'd like to know what needs to be covered with the exchanges.

**Comment by notadamking** [comment]
@funlyonions it is a great start, though many of the tests are not testing useful aspects of the components, and some are incorrect altogether. Unfortunately, I cannot get this merged today, I will have to start a formal review this week.

**Comment by funlyonions** [comment]
So, what would be considered useful?

**Comment by notadamking** [comment]
Useful meaning it tests that the functionality of a component is working as expected, and that there is no problems in the logic.

E.g. if you look at `test_fbm_exchange`, there isn't much useful being tested, however we are testing that the default values have not changed.

```
assert exchange._hurst == 0.61
```

This is not useful.

**Comment by funlyonions** [comment]
Got it. I'll revise.

**Comment by notadamking** [comment]
Unfortunately most of these tests will not be useful after the latest changes to the framework. I apologize.

**Pull request closed without merging**
